"""add room capacity and beds

Revision ID: 342713d9f1d9
Revises: 9267ddc80662
Create Date: 2026-03-08 20:07:42.003591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342713d9f1d9'
down_revision = '9267ddc80662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('beds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('beds')
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
